### ISSUE TITLE
Reset specialization every time you level up

### ISSUE THREAD

**Issue by NesinAlex** [Thordekk/Dekk-Core-Donator-Bugtracker#599] opened 2023-05-17 18:29 UTC
Before level up
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/473e2955-4f19-47fd-b763-b2f8e8ca046c)

After level up
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/4975e9fa-155a-4e75-8309-ceaa46a3358c)
![image](https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/assets/42183646/1f2836bd-145d-485b-9d20-49c127e034bb)

**Comment by ahoffman1** [comment] 2023-05-17 20:42
Duplicate of https://github.com/Thordekk/Dekk-Core-Donator-Bugtracker/issues/556

**Comment by ahoffman1** [comment] 2023-05-21 19:09
fixed

**Closed by ahoffman1** 2023-05-21 19:09 UTC
